### ISSUE TITLE
One OEM key was not accepted

### ISSUE THREAD

**Issue by malvarenga123** [alex-free/open95keygen#2]
OEM Product Key: 22495-OEM-0081478-38834

That key was not accepted when installing W95 OSR2.5 OEM (win95c_osr2.5_OEM-FullSetup_PLUS_cd_type09_19971201.iso).
I generated a new key (OEM Product Key: 09496-OEM-0091004-83890) and it worked.

**Comment by alex-free** [comment]
Thank you for the report! This has been fixed in v1.0.3
